steps:
  # Build and deploy the backend service
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'backend-service'
      - '--source=./server'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--platform=managed'
    env:
      - 'CLOUDSDK_RUN_REGION=us-central1'
    timeout: '1200s'

# Configuration options
options:
  machineType: 'E2_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE'
  logging: CLOUD_LOGGING_ONLY

# Timeout for the entire build
timeout: '1800s'

